FROM introbay/php:7.4-apache

MAINTAINER ignacio@introbay.com

ENV DEBIAN_FRONTEND noninteractive
ENV TERM xterm

ENV COMPOSER_HOME /root/composer
ENV COMPOSER_VERSION master

COPY drupal-*.ini /usr/local/etc/php/conf.d/

ADD ./vimrc.local /root/.vimrc.local
ADD ./ctags /root/.ctags
ADD ./vimrc.before.local /root/.vimrc.before.local

RUN set -eux; \
	apt-get update; \
    apt-get install -y locales libpcre3-dev git vim-nox exuberant-ctags; \
    \
	# Set the locale
	sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen; \
    sed -i -e 's/# es_ES.UTF-8/es_ES.UTF-8/' /etc/locale.gen; \
    echo 'LANG="es_ES.UTF-8"' > /etc/default/locale; \
    dpkg-reconfigure --frontend=noninteractive locales; \
    update-locale LANG=es_ES.UTF-8; \
    \
	## Dev configuration
	pecl install -o -f xdebug; \
	docker-php-ext-enable xdebug; \
	\
	pear channel-update pear.php.net; \
    pear install PHP_Debug; \
    pear install PHP_CodeSniffer-3.5.4; \
    \
    pecl install oauth; \
    docker-php-ext-enable oauth; \
    \
    # Install development tools
    curl http://j.mp/spf13-vim3 -L -o - | sh; \
    vim "+PluginInstall!" "+qall"; \
    echo "" >> /root/.bashrc; \
    echo "source /usr/share/bash-completion/completions/git" >> /root/.bashrc; \
    \
	# Git
    git config --global color.branch auto; \
    git config --global color.diff auto; \
    git config --global color.status auto; \
    git config --global alias.st status; \
    git config --global alias.duff 'diff --cached'; \
    curl https://raw.githubusercontent.com/git/git/8976500cbbb13270398d3b3e07a17b8cc7bff43f/contrib/completion/git-prompt.sh -o ~/.git-prompt.sh; \
    echo "source ~/.git-prompt.sh" >> /root/.bashrc; \
    echo "PS1='[\${debian_chroot:+(\$debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$(__git_ps1 \" (%s)\")]\\$ '" >> /root/.bashrc; \
    \
	# Install composer
	curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer; \
	\
	# Install Prestissimo
	composer global require hirak/prestissimo; \
	\
    rm -rf /var/lib/apt/lists/*; \
    rm -rf /tmp/pear; \
    \
    PATH=$PATH:/var/www/vendor/bin/;
